collections:
  '1x':
    output: true
    permalink: /:path:output_ext
  '13':
    output: true
    permalink: /:path:output_ext
version: '1.3'
package_version: '1.3.1'
sg_download_link: 'http://packages.couchbase.com/releases/couchbase-sync-gateway/1.3.1/'
sg_package_name: 'couchbase-sync-gateway-community_1.3.1-16_x86_64'
