collections:
  '20':
    output: true
    permalink: /:path:output_ext
version: '2.0'
ios_dev_build: '2.0DB007'
android_dev_build: '2.0.0-DB008'
dev_build_release_date: 'May 15, 2017'
objc_dev_build_download_link: https://packages.couchbase.com/releases/couchbase-lite/ios/2.0DB7/couchbase-lite-objc_community_2.0DB007.zip
swift_dev_build_download_link: https://packages.couchbase.com/releases/couchbase-lite/ios/2.0DB7/couchbase-lite-swift_community_2.0DB007.zip
references:
  objc: 'http://docs.couchbase.com/mobile/2.0/couchbase-lite-objc/db007/'
  swift: 'http://docs.couchbase.com/mobile/2.0/couchbase-lite-swift/db007/docsets/CouchbaseLiteSwift.docset/Contents/Resources/Documents/'
  csharp: 'http://docs.couchbase.com/mobile/2.0/couchbase-lite-net/db008/'
  java: 'http://docs.couchbase.com/mobile/2.0/couchbase-lite-java/db008/'
sg_download_link: 'https://packages.couchbase.com/releases/couchbase-sync-gateway/1.5.0-dp001/couchbase-sync-gateway-community_1.5.0-377_x86_64'